# File: .github/workflows/experiment.yml

name: experiment

on:
  schedule:
    - cron: '* * * * *' # Runs every minute
  workflow_dispatch: # Enables manual triggers

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: experiment
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python -m venv venv || true
          source ./venv/bin/activate || true
          python -m pip install -U aider-chat || true
          git config --local user.email "lloydchang@gmail.com" || true
          git config --local user.name "lloydchang" || true
          echo "edit main.py and improve it to make the world's best texas hold'em poker game" | aider --analytics-disable --yes --model gemini/gemini-1.5-flash-latest --map-tokens 1024

      - name: Commit and Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

permissions:
  contents: write  # Allow write access to repository contents
  pull-requests: write  # Allow pull requests to be created if needed
